### ISSUE TITLE
Treasure buying crashes the the bot

### ISSUE THREAD

**Issue by NekoMeowzers** [the-world-machine/bot#13]
so when you buy treasures with more than like 150 or 200 billion it starts crashing the bot and making it go offline for a few minutes and it takes sheer luck to let you buy stuff with more than 200 billion or so since thats when i started noticing it messing up ![image](https://github.com/user-attachments/assets/244bedf3-e813-4ca7-bbd8-31bc7ecc4dc9)

**Comment by axiinyaa** [comment]
![image](https://github.com/user-attachments/assets/c27576b7-52cd-48df-8544-7c20ad5a8e18)
yeah i figured it out, The way i was calculating the max buy/sell price made it really really *really* slow for large numbers. to fix i'm using a built in python function to calculate the price of buying as much as possible which is a LOT faster. Also introduced a limit (while i'm aware is annoying) does help make it a little faster as well
